### ISSUE TITLE
M jannaschii morph metabolite duplicates

### ISSUE THREAD

**Issue by marichards** [kingb12/model-morphing#7]
The current MJ morph has a number of duplicated compounds (e.g. 3 versions of cytosolic H2O). Not sure why it's doing this, but it shouldn't. Wouldn't be surprised if it results in duplicated reaction names too.

**Comment by kingb12** [comment]
This should be fixed now! (for future morphs at least). Our source model and reconstruction models referenced compound IDs in different biochemistries. The source model (MaripaludisModelRevised, v4, in MODEL-MORPHING-TEST-GROUND (ws 9145)) has been updated to reference the same biochemistry as automatic reconstructions. From what I could tell, there was no effect other than semantic on the source model. 

(No code change, a data fix).
